application: cr-status
version: 1
runtime: python27
threadsafe: true
api_version: 1

default_expiration: "30d"

libraries:
- name: webapp2
  version: "latest"
- name: django
  version: "latest" #version: "1.3"

env_variables:
  DJANGO_SETTINGS_MODULE: 'settings'

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.csv$
- ^(.*/)?.*\.psd$
- ^(.*/)?.*\.sql[3]$
- ^(.*/)?.*\.sh$
- ^(.*/)?.*\.scss$

handlers:
- url: /favicon\.ico
  static_files: static/img/chrome_logo.svg
  upload: static/img/chrome_logo\.svg

- url: /static
  static_dir: static

- url: /admin/.*
  script: google.appengine.ext.admin.application
  login: admin

- url: /newfeature
  script: server.app
  login: admin

- url: /.*
  script: server.app


