name: Continuous Integration
on:
  push:
    branches:
      - main
      - github-actions # TODO: remove
jobs:
  node_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '8.x'

      - name: set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '2.7'

      - name: pre-installation
        run: |
          curl https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-353.0.0-linux-x86_64.tar.gz | tar -zxf > /dev/null
          ./$HOME/google-cloud-sdk/install.sh
          source ~/.bashrc
          gcloud components update -q
          gcloud components install app-engine-python beta cloud-datastore-emulator app-engine-python-extras
          gcloud version

      - name: installation
        run: |
          npm install -g gulp
          npm install
          npm run ci-dep

      - name: lint
        run: npm run lint

      - name: test
        run: npm run start-emulator

      - name: build
        run: npm run build

      - name: clean up
        run: df -h
