name: Continuous Integration
on:
  push:
    branches:
      - main
      - github-actions # TODO: remove
jobs:
  node_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '8.x'

      - name: set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '2.7'

      - name: pre-installation
        run: |
          sudo snap remove google-cloud-sdk
          curl -s https://sdk.cloud.google.com > install-gcloud.sh
          bash ./install-gcloud.sh --disable-prompts --install-dir=$(HOME) > /dev/null
          rm -f ./install-gcloud.sh
          source $HOME/google-cloud-sdk/path.bash.inc
          gcloud components update -q
          gcloud components install app-engine-python beta cloud-datastore-emulator app-engine-python-extras
          gcloud version

      - name: installation
        run: |
          npm install -g gulp
          npm install
          npm run ci-dep

      - name: lint
        run: npm run lint

      - name: test
        run: gcloud beta emulators datastore start --host-port=:15606 --no-store-on-disk --consistency=1.0

      - name: build
        run: npm run build

      - name: clean up
        run: df -h
