name: Continuous Integration
on:
  push:
    branches:
      - main
      - github-actions # TODO: remove
jobs:
  node_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '8.x'

      - name: set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '2.7'

      - name: pre-installation
        run: |
          echo "deb https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
          apt-get update -qqy && apt-get install -qqy \
          google-cloud-sdk \
          google-cloud-sdk-app-engine-python \
          google-cloud-sdk-beta \
          google-cloud-sdk-cloud-datastore-emulator \
          google-cloud-sdk-app-engine-python-extras
          gcloud version

      - name: installation
        run: |
          npm install -g gulp
          npm install
          npm run ci-dep

      - name: lint
        run: npm run lint

      - name: test
        run: npm run start-emulator

      - name: build
        run: npm run build

      - name: clean up
        run: df -h
